name: Auto-Move Issues and PRs to Project Beta

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  move-to-project:
    runs-on: ubuntu-latest

    steps:
      # Mover Issue ou PR para o Projeto Beta com Base no Label
      - name: Mover para Projeto Beta com Base no Label
        uses: actions/add-to-project@v1.0.2
        with:
          # Substitua pela URL completa do seu projeto Beta
          project-url: https://github.com/users/alepmedeiros/projects/23
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Labels que acionam a movimentação
          labeled: bug, feature, urgent, enhancement
          # Operador lógico para combinar labels (OR = qualquer label move a issue)
          label-operator: OR
