name: Auto-Add Issues to Project Board with Labels

on:
  issues:
    types: [labeled]

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Adicionar Issue ao Quadro
        uses: alstr/remove-project-card@v1
        with:
          project: "21" # Substitua pelo ID do seu projeto
          column: >
            ${{ 
              github.event.label.name == 'bug' && 'Backlog' || 
              github.event.label.name == 'feature' && 'To Do' || 
              'In Progress' 
            }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
