name: Auto-Move Issues to Project Columns

on:
  issues:
    types: [labeled]

jobs:
  move-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Mover Issue para o Projeto Beta com Base no Rótulo
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/alepmedeiros/projects/23 # Substitua pelo URL do projeto Beta
          github-token: ${{ secrets.GITHUB_TOKEN }}
          field-value: >
            ${{ 
              github.event.label.name == 'bug' && 'Backlog' || 
              github.event.label.name == 'feature' && 'To Do' || 
              github.event.label.name == 'urgent' && 'In Progress' || 
              github.event.label.name == 'enhancement' && 'Enhancements' || 
              'General' 
            }}
